package org.literacyapp.chat.dao;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import org.literacyapp.chat.model.TextMessage;

import org.literacyapp.chat.dao.TextMessageDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig textMessageDaoConfig;

    private final TextMessageDao textMessageDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        textMessageDaoConfig = daoConfigMap.get(TextMessageDao.class).clone();
        textMessageDaoConfig.initIdentityScope(type);

        textMessageDao = new TextMessageDao(textMessageDaoConfig, this);

        registerDao(TextMessage.class, textMessageDao);
    }
    
    public void clear() {
        textMessageDaoConfig.getIdentityScope().clear();
    }

    public TextMessageDao getTextMessageDao() {
        return textMessageDao;
    }

}
