package org.literacyapp.chat.dao;

import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;

import org.literacyapp.chat.model.TextMessage;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "TEXT_MESSAGE".
*/
public class TextMessageDao extends AbstractDao<TextMessage, Void> {

    public static final String TABLENAME = "TEXT_MESSAGE";

    /**
     * Properties of entity TextMessage.<br/>
     * Can be used for QueryBuilder and for referencing column names.
    */
    public static class Properties {
        public final static Property Text = new Property(0, String.class, "text", false, "TEXT");
    };


    public TextMessageDao(DaoConfig config) {
        super(config);
    }
    
    public TextMessageDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"TEXT_MESSAGE\" (" + //
                "\"TEXT\" TEXT NOT NULL );"); // 0: text
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"TEXT_MESSAGE\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, TextMessage entity) {
        stmt.clearBindings();
        stmt.bindString(1, entity.getText());
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, TextMessage entity) {
        stmt.clearBindings();
        stmt.bindString(1, entity.getText());
    }

    @Override
    public Void readKey(Cursor cursor, int offset) {
        return null;
    }    

    @Override
    public TextMessage readEntity(Cursor cursor, int offset) {
        TextMessage entity = new TextMessage( //
            cursor.getString(offset + 0) // text
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, TextMessage entity, int offset) {
        entity.setText(cursor.getString(offset + 0));
     }
    
    @Override
    protected final Void updateKeyAfterInsert(TextMessage entity, long rowId) {
        // Unsupported or missing PK type
        return null;
    }
    
    @Override
    public Void getKey(TextMessage entity) {
        return null;
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
}
